# Generated by Django 4.0.6 on 2022-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('user_name', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
