# Generated by Django 4.0.6 on 2022-08-31 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_profile_delete_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField(blank=True, help_text='Message text')),
                ('subject', models.TextField(blank=True, help_text='Message text')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.profile')),
            ],
        ),
    ]
