# Generated by Django 4.0.6 on 2022-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.TextField(blank=True, help_text='Phone numbers', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
