# Generated by Django 4.0.6 on 2022-09-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_message_receiver_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
