# Generated by Django 4.0.6 on 2022-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_rename_phone_number_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'creation_time'], name='counter_mes_receive_52e500_idx'),
        ),
    ]
