# Generated by Django 4.1.1 on 2022-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_message_read_message_counter_mes_receive_52e500_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
